### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by hokiespurs** [hokiespurs/images-in-a-potree#1]
- [x] make folder structure
- [x] make sample dataset w/ undistorted images, thumbnails, and camera poses + fov
- [x] figure out how to host pointcloud on external server with potree
- [x] figure out camera rotations in Three.js vs photoscan
- [x] make cesium work? Yes, didn't like it
- [x] make buttons work in dropdown
- [x] document how to get data ready for this workflow
- [x] can I make https work with http on github without disabling browser safety? no, just host on research.engr
- [x] measureTool Buttons
- [x] `potree_map` toggle button
- [x] ortho on map?

**Comment by hokiespurs** [comment]
## SERVER FOLDER STRUCTURE
```
|-- http://research.engr.oregonstate.edu/lidar/pointcloud/*DATANAME*
    |-- index.html
    |-- assets
    |   |-- cameras.js
    |   |-- cloud.js
    |   |-- sources.json
    |   |-- 01_IMAGES
    |   |   |-- all undistorted images
    |   |-- 02_THUMBNAILS
    |   |   |-- all thumbnail images
    |   |-- 03_POSES
    |   |   |-- opk.txt
    |   |-- 04_POINTCLOUD
    |   |   |-- data.las
    |   |-- 05_POTREEDATA
    |       |-- potree organized data structure
    |-- css
    |   |-- main.css
    |-- doc
    |   |-- img
    |-- js
    |   |-- potreepointcloud.js
    |   |-- sfmcameras.js
    |-- libs
        |-- all javascript and css libraries
```

## DEVELOPMENT FOLDER STRUCTURE
```
|-- githubname
    |-- index.html
    |-- assets
    |   |-- cameras.js
    |   |-- cloud.js
    |   |-- sources.json
    |-- css
    |   |-- main.css
    |-- doc
    |   |-- img
    |-- js
    |   |-- potreepointcloud.js
    |   |-- sfmcameras.js
    |-- libs
        |-- all javascript and css library dependencies
```

**Comment by hokiespurs** [comment]
### Add Measurement Buttons
```js
let measuringTool = new Potree.MeasuringTool(viewer);
let measurement = measuringTool.startInsertion({
					showDistances: false,
					showAngles: true,
					showArea: false,
					closed: true,
					maxMarkers: 3,
					name: 'Angle'});
```

**Comment by hokiespurs** [comment]
## Processing Steps
1) If images have duplicate names, rename them using the following script in the console
```python
chunk = PhotoScan.app.document.chunk
i=0
for camera in chunk.cameras:
   camera.label='Undist_' + str(i).zfill(4) + '.JPG'
   i=i+1
```
2) File -> Export -> Undistort Photos
- Undistort images to 01_IMAGES.  
- if renamed images, replace `{filename}.{ext}` with `{camera}` in the GUI 
3) File -> Export -> Cameras as `omega phi kappa` into `03_POSES/opk.txt'
4) Tools -> Camera Calibration -> Calibrated -> Saveas -> `03_POSES/camcal.xml`
5) Shrink Image to make thumbnail, and resize the image so its a power of 2
- in Matlab, navigate to `01_IMAGES`, then run `shrinkImages.m`
- optionally, change the `SMALLSIZE` and `BIGSIZE` depending on preference
6) Convert OPK into RPY and save as javascript file 
- I was pressed for time, and writing this in Matlab was easier than reading the opk.txt and camcal.xml in javascript
- edit constants, then run `convertOPK2RPY.m`
```matlab
FNAME = 'G:\www_lidar\pointcloud\divicarina\assets\03_POSES\opk.txt';
IMAGELOCATION = 'http://research.engr.oregonstate.edu/lidar/pointcloud/divicarina/assets/';
FOCAL = 3093.95123;
IMAGEDIM = [4000 3000];
```
7) Edit index.html to change title, attribution, logos, and info
8) Process Data with PotreeConverter into 05_POTREEDATA
9) Edit `cloud.js` so the full filepath is in there
### Before
```js
{
    "version": "1.7",
    "octreeDir": "data",
    "projection": "+proj=utm +zone=20 +ellps=GRS80 +datum=NAD83 +units=m +no_defs",
    "points": 26829344,
...
```
### After
```js
    {
    "version": "1.7",
    "octreeDir": "http://research.engr.oregonstate.edu/lidar/pointcloud/solarpanels/assets/05_POTREEDATA/pointclouds/index/data",
    "projection": "+proj=utm +zone=20 +ellps=GRS80 +datum=NAD83 +units=m +no_defs",
    "points": 26829344,
...
```
10) Add a file `.htaccess` to the `assets` folder
```
CheckSpelling Off
Header set Access-Control-Allow-Origin "*"
```

**Comment by hokiespurs** [comment]
## APPEARANCE
- EDL toggle button
- Point Budget slider
- Point Size slider
- Image Plane Opacity slider
- RGB/Elevation toggle
- elevation colormap min/max slider

## INFO
- attribution
- metadata into
- share links

**Comment by hokiespurs** [comment]
```
scene.pointclouds.forEach( pc => pc.material.pointColorType = Potree.PointColorType.RGB );
scene.pointclouds.forEach( pc => pc.material.pointColorType = Potree.PointColorType.ELEVATION );
scene.pointclouds.forEach( pc => pc.material.pointColorType = Potree.PointColorType.RGB_HEIGHT );

viewer.scene.pointclouds[0].material.elevationRange = [minZ, maxZ];
viewer.scene.pointclouds[0].material.weightElevation = weightZ;
viewer.scene.pointclouds[0].material.weightRGB = weightRGB;

```

**Comment by hokiespurs** [comment]
- [x] make appearance layout
- [x] make appearance buttons work
- [x] add filter by point functionality
- [x] lookAt that point as it steps through images
- [x] filter cameras by which see a certain point
- [x] button to clear filter
- [x] make modal popup for info
- [ ] readme and howto on github
- [x] add download pointcloud/ortho button
- [x] Coordinate Transformation to leaflet map using proj4 to WGS84
- [x] camera footprint into leaflet using mean elevation of scene as Z:
```
viewer.scene.pointclouds[0].material.elevationRange
```
- [x] use pinhole camera model and redraw every x milliseconds

**Comment by hokiespurs** [comment]
- [x] Add error handling to make sure that the jquery.ui range slider doesnt crash when the pointcloud hasnt loaded yet
- [x] change default points to 1000000, HQ, and lighting off
- [ ] add intro.js

**Comment by hokiespurs** [comment]
- [x] Make HowTo
  - Page layout (Map, Pointcloud, Image Pyramids, Toolbar)
  - Navigation (mouse buttons and what they do)
  - Map (toggle, resize, legend)
  - Image Pyramids (show/describe pyramid, toggle pyramids)
  - "Look through" functionality (Click image pyramid, mouse buttons)
  - "Look At" functionality (How-to)
  - Measure buttons
  - Appearance tools
  - Download button
  - Info Button
  - Help Button

```
LAYOUT
- map, toolbar, 3d scene

IMAGE PYRAMIDS
- image pyramids represent where an image was taken

SIMPLIFY THE LAYOUT
- toggle images
- toggle map

NAVIGATION
- Scroll Zoom
- Left Mouse to Orbit
- Right Mouse to Translate
- Double click to zoom to a point

NAVIGATION TO LOOK-THROUGH
- Two ways to enter pyramid mode
 1) Click pyramid
 2) Click Arrow Key to get the previous or next image

NAVIGATION IN LOOK-THROUGH MODE
- Left mouse looks around
- Scroll wheel zooms
- Right mouse translates and exits the view

MAP LAYOUT
- blue is current camera youre looking through
- orange is the rendering camera
- dot is for rendering camera position

MEASURE BUTTONS

APPEARANCE TOOLS

DOWNLOAD BUTTON
```

**Comment by hokiespurs** [comment]
consolidated into wiki and readme.md
